apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc1
  labels:
    name: grafpvc1
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi





