apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: mygrafana
spec:
  selector:
    env: grafana
  type: NodePort
  ports:
    - port: 3000
      nodePort: 32000





    