apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels:
    app: myprometheus
spec:
  selector:
    env: prometheus
  type: NodePort
  ports:
    - port: 9090
      nodePort: 31000
    